# Generated by Django 2.0.1 on 2018-08-04 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer1', models.CharField(blank=True, max_length=255, verbose_name='Первый')),
                ('answer2', models.CharField(blank=True, max_length=255, verbose_name='Второй')),
                ('answer3', models.CharField(blank=True, max_length=255, verbose_name='Третий')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL, verbose_name='О ком ответ')),
            ],
        ),
    ]
